### ISSUE TITLE
`README.rst` -> `README.md`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/3D_animations#2]
Could we convert the readme to markdown as is the case for the rest of the organisation's repos? I feel people are much more used to markdown compared to `rst`.

**Comment by josuemtzmo** [comment]
Ok, I will do it. 

Just for reference, the initial plan was to integrate this repo to host a GitHub website in the future with the animations, but that can also be implemented using markdown.

**Comment by navidcy** [comment]
Well, if it makes things harder for this gh website page then don't bother. I didn't think about that...

**Comment by josuemtzmo** [comment]
Nope, I'm just more familiar with `rst` for documentation, but It's the same process.

**Comment by navidcy** [comment]
If we'll keep it `.rst`, then can you make format the filenames to be in code? E.g., `filename.mov`? (I just don't know how to work with `.rst` files)

**Comment by josuemtzmo** [comment]
I don't understand what you mean...

**Comment by navidcy** [comment]
> I don't understand what you mean...

See #10.
